### ISSUE TITLE
Increase node version floor and cut new major once QUERY is supported?

### ISSUE THREAD

**Issue by jonchurch** [jshttp/methods#27]
The fallback methods in https://github.com/jshttp/methods/blob/master/index.js#L22 do not encompass the new QUERY method.

We could use code to include it if the Node version you're running includes it, but I think a new major would be more appropriate if we have differences in `http.METHODS` between node majors. Not sure this has ever happened before.

See https://github.com/expressjs/express/issues/5615

related: https://github.com/expressjs/express/pull/5628

**Comment by dougwilson** [comment]
That list of methods in this module is only supposed to be the ones supported by Node.js 0.10. If you are going to make a ner major, drop 0.10 and remove that static list, as it is only needed for supprt Node.js 0
10

**Comment by dougwilson** [comment]
And at that point, why bother with the module, just use the http module exports directly in express and stuff. This module was only made for shimming Node.js 0.10 support

**Comment by jonkoops** [comment]
I think this can be closed considering we're dropping this module for Express v5, see #127
